name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  Build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Restore Gradle state from cache
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25

    - name: Build with Gradle
      run: |
        ./gradlew build
